server:
  port: 8778

spring:
  application:
    name: spring-cloud-stream-rockermq-consumer
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.1.203:7121;192.168.1.203:7122;192.168.1.203:7123
        bindings:
          input1:
            consumer:
              orderly: true
      bindings:
        input1:
          group: binder-group
          destination: test-topic

management:
  endpoint:
    health:
      show-details: always
